[build]
  command = "npm run prerender"
  functions = "./functions"
  publish = "dist/cifrado-ssr/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/angular-builder"
  status = 200
