[[redirects]]
  from = "/*"
  to = "./netlify/functions/start"
  status = 200

[build]
  command = "npm run build:ssr && npm run copy:files"
  functions = "netlify/functions/"

[[plugins]]
  package = "@netlify/plugin-angular-universal"
  [plugins.inputs]
    projectName = "cifrado-ssr"

[functions]
  included_files = ["dist/**"]
