[[redirects]]
  from = "/*"
  to = "./netlify/functions/start"
  status = 200

[build]
  command = "npm run build:ssr && npm run copy:files"
  functions = "netlify/functions/"
  publish = "dist/cifrado-ssr/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[functions]
  included_files = ["dist/**"]
