[build]
  command = "npm run prerender  ---prod && ng run cifrado-ssr:serverless:production"
  publish = "dist/cifrado-ssr/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
